# BlightedMC - Made with <3 by Moussa

############################################################
# +------------------------------------------------------+ #
# |                       General                        | #
# +------------------------------------------------------+ #
############################################################

default_max_mana: 100.0
default_mana_regeneration-rate: 1.0
default_player_health: 20.0

# Players will have a banner in their helmet slot upon joining for the first time
banners_on_join: true

############################################################
# +------------------------------------------------------+ #
# |                Fishing System                        | #
# +------------------------------------------------------+ #
############################################################

# The probability of fishing blighted loots vs. vanilla fishing loots.
# The range is between 0.0 and 1.0. Default is 0.50 (50% for vanilla, 50% for blighted loots).
# This chance doesn't affect the probability of getting specific blighted loot.

# The chance of getting custom loot (between 0.0 and 1.0, default is 0.50)
custom_loot_chance: 0.50

############################################################
# +------------------------------------------------------+ #
# |                        Server                        | #
# +------------------------------------------------------+ #
############################################################
